### ISSUE TITLE
⚠ Warns reported

### ISSUE THREAD

**Issue by vv-monsalve** [rfuenzalida/AntonFont#12]
`.notdef` glyph should have a drawing

<details>
<summary>⚠ <b>WARN:</b> Font contains .notdef as first glyph?</summary>

* [com.google.fonts/check/mandatory_glyphs](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/mandatory_glyphs)
<pre>--- Rationale ---

The OpenType specification v1.8.2 recommends that the first glyph is the
.notdef glyph without a codepoint assigned and with a drawing.

https://docs.microsoft.com/en-us/typography/opentype/spec
/recom#glyph-0-the-notdef-glyph

Pre-v1.8, it was recommended that a font should also contain a .null, CR and
space glyph. This might have been relevant for applications on MacOS 9.

</pre>

* ⚠ **WARN** Font should contain the .notdef glyph as the first glyph, it should not have a Unicode value assigned and should contain a drawing.

</details>

**Comment by vv-monsalve** [comment]
This check is intended to catch and warn for consecutive line segments which have the same or a very similar angle.

<details>
<summary>⚠ <b>WARN:</b> Do any segments have colinear vectors?</summary>

* [com.google.fonts/check/outline_colinear_vectors](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/<Section: Outline Correctness Checks>.html#com.google.fonts/check/outline_colinear_vectors)
<pre>--- Rationale ---

This test looks for consecutive line segments which have the same angle. This
normally happens if an outline point has been added by accident.

This test is not run for variable fonts, as they may legitimately have colinear
vectors.


</pre>

* ⚠ **WARN** The following glyphs have colinear vectors:
	* uni0181: L<<426.0,1760.0>--<426.0,1760.0>> -> L<<426.0,1760.0>--<903.0,1760.0>>
	* uni018A: L<<427.0,1760.0>--<427.0,1760.0>> -> L<<427.0,1760.0>--<911.0,1760.0>>
	* uni01A4: L<<427.0,1760.0>--<427.0,1760.0>> -> L<<427.0,1760.0>--<892.0,1760.0>>
	* uni01AC: L<<416.0,1760.0>--<416.0,1760.0>> -> L<<416.0,1760.0>--<980.0,1760.0>>
	* uni028C: L<<477.0,1002.0>--<463.0,757.0>> -> L<<463.0,757.0>--<380.0,0.0>>
	* uni028C: L<<563.0,0.0>--<489.0,759.0>> -> L<<489.0,759.0>--<477.0,1002.0>>
	* uni1E7D: L<<381.0,1500.0>--<455.0,741.0>> -> L<<455.0,741.0>--<467.0,498.0>>
	* uni1E7D: L<<467.0,498.0>--<481.0,743.0>> -> L<<481.0,743.0>--<564.0,1500.0>>
	* uni1E7F: L<<381.0,1500.0>--<455.0,741.0>> -> L<<455.0,741.0>--<467.0,498.0>>
	* uni1E7F: L<<467.0,498.0>--<481.0,743.0>> -> L<<481.0,743.0>--<564.0,1500.0>> and 3 more. [code: found-colinear-vectors]

</details>

**Comment by vv-monsalve** [comment]
<details>
<summary>⚠ <b>WARN:</b> Do outlines contain any jaggy segments?</summary>

* [com.google.fonts/check/outline_jaggy_segments](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/<Section: Outline Correctness Checks>.html#com.google.fonts/check/outline_jaggy_segments)
<pre>--- Rationale ---

This test heuristically detects outline segments which form a particularly
small angle, indicative of an outline error. This may cause false positives in
cases such as extreme ink traps, so should be regarded as advisory and backed
up by manual inspection.


</pre>

* ⚠ **WARN** The following glyphs have jaggy segments:
	* Eng: L<<440.0,1760.0>--<602.0,917.0>>/L<<602.0,917.0>--<602.0,1760.0>> = 10.877964253816563
	* Eng: L<<577.0,105.0>--<422.0,880.0>>/L<<422.0,880.0>--<422.0,0.0>> = 11.309932474020227
	* K: L<<426.0,1760.0>--<426.0,1055.0>>/L<<426.0,1055.0>--<590.0,1760.0>> = 13.095479093415124
	* K: L<<620.0,0.0>--<428.0,852.0>>/L<<428.0,852.0>--<428.0,0.0>> = 12.699584489597349
	* M: L<<1128.0,0.0>--<1128.0,1268.0>>/L<<1128.0,1268.0>--<926.0,0.0>> = 9.051501636066247
	* M: L<<610.0,0.0>--<396.0,1268.0>>/L<<396.0,1268.0>--<396.0,0.0>> = 9.579521286731712
	* N: L<<440.0,1760.0>--<602.0,917.0>>/L<<602.0,917.0>--<602.0,1760.0>> = 10.877964253816563
	* N: L<<598.0,0.0>--<422.0,880.0>>/L<<422.0,880.0>--<422.0,0.0>> = 11.309932474020227
	* Nacute: L<<440.0,1760.0>--<602.0,917.0>>/L<<602.0,917.0>--<602.0,1760.0>> = 10.877964253816563
	* Nacute: L<<598.0,0.0>--<422.0,880.0>>/L<<422.0,880.0>--<422.0,0.0>> = 11.309932474020227 and 202 more. [code: found-jaggy-segments]

</details>

**Comment by vv-monsalve** [comment]
<details>
<summary>⚠ <b>WARN:</b> Do outlines contain any semi-vertical or semi-horizontal lines?</summary>

* [com.google.fonts/check/outline_semi_vertical](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/<Section: Outline Correctness Checks>.html#com.google.fonts/check/outline_semi_vertical)
<pre>--- Rationale ---

This test detects line segments which are nearly, but not quite, exactly
horizontal or vertical. Sometimes such lines are created by design, but often
they are indicative of a design error.

This test is disabled for italic styles, which often contain nearly-upright
lines.


</pre>

* ⚠ **WARN** The following glyphs have semi-vertical/semi-horizontal lines:
	* Abreve: L<<110.0,2205.0>--<366.0,2204.0>>
	* Abreve: L<<636.0,2204.0>--<892.0,2205.0>>
	* Ebreve: L<<58.0,2205.0>--<314.0,2204.0>>
	* Ebreve: L<<584.0,2204.0>--<840.0,2205.0>>
	* Gbreve: L<<109.0,2205.0>--<365.0,2204.0>>
	* Gbreve: L<<635.0,2204.0>--<891.0,2205.0>>
	* Ibreve: L<<-154.0,2205.0>--<102.0,2204.0>>
	* Ibreve: L<<372.0,2204.0>--<628.0,2205.0>>
	* Obreve: L<<113.0,2205.0>--<369.0,2204.0>>
	* Obreve: L<<639.0,2204.0>--<895.0,2205.0>> and 194 more. [code: found-semi-vertical]

</details>

**Comment by rfuenzalida** [comment]
Hi Viviana, did a check visual check on this issues and I think that for the most part most of the warns were resolved. I'm going to update the source file with the corrections.
