### ISSUE TITLE
🔥 FAIL: Check glyphs do not have duplicate components which have the same x,y coordinates.

### ISSUE THREAD

**Issue by vv-monsalve** [rfuenzalida/AntonFont#3]
<details>
<summary>🔥 <b>FAIL:</b> Check glyphs do not have duplicate components which have the same x,y coordinates.</summary>

* [com.google.fonts/check/glyf_non_transformed_duplicate_components](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/glyf.html#com.google.fonts/check/glyf_non_transformed_duplicate_components)
<pre>--- Rationale ---

There has been cases in which fonts had faulty double quote marks, with each of
them containing two single quote marks as components with the same x, y
coordinates which makes them visually look like single quote marks.

This check ensures that glyphs do not contain duplicate components which have
the same x,y coordinates.

</pre>

* 🔥 **FAIL** The following glyphs have duplicate components which have the same x,y coordinates:
	* {'glyph': 'guillemotleft.case', 'component': 'guilsinglleft', 'x': 0, 'y': 0} and {'glyph': 'guillemotright.case', 'component': 'guilsinglright', 'x': 0, 'y': 0} [code: found-duplicates]

</details>

**Comment by rfuenzalida** [comment]
This already fixed on the new file I'm going to upload.
